#SCRIPT TO CREATE ALL parallel.*() VARIATIONS OF FUNCTIONS
#This script is generally run locally and `output_file` is generated based on
#   the saved location of the package.

#Example format for sample_lsm() function
# parallel.sample_lsm <- function(..., split_on) {
#   result <- format_args(..., split_on = split_on, func = landscapemetrics::sample_lsm)
#   return(result)
# }

#TXT/R File to Write Functions To
output_file <- file.path(rstudioapi::getActiveDocumentContext()$path |> dirname() |> dirname(), 'R/lsm-funcs.R')

library(landscapemetrics)

#Text to Include at the Top of the File
file_top <- "#' @include parallel-lsm.R
#' @noRd
NULL

#This file is automatically generated using create-lsm-funcs.R
"


#Functions/Objects to Exclude
exclude <- c(
  'lsm_abbreviations_names', 'landscape', 'augusta_nlcd', 'podlasie_ccilc',
  'options_landscapemetrics', 'show_patches', 'show_cores', 'show_correlation', 'show_lsm'
)

#Function to Concat. The Formatting
func_format <- function(func) {paste0(
"#' @rdname parallel.lsm
#' @export
parallel.", func, " <- function(..., split_on = NULL, join_tbl = TRUE) {
  result <- lsm_format_run(..., split_on = split_on, join_tbl = join_tbl, func = landscapemetrics::", func, ")
  return(result)
}
")}

#List Everything in LSM + Filter
funcs <- getNamespaceExports("landscapemetrics")
#funcs <- ls('package:landscapemetrics')
funcs <- funcs[!funcs %in% exclude]

#Format as Functions
funcs <- lapply(funcs, func_format)

#Write to File
funcs <- append(file_top, funcs)
writeLines(text = paste(funcs, collapse = '\n'), con = output_file)
